In [12]:
import json

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import torch

In [13]:
def bytes_moved(shape: int, dtype: torch.dtype = torch.float32) -> float:
    return float(3 * shape * dtype.itemsize / 1e9)

In [14]:
path = "logs/2026-10-02_14-29-18_41b9e00b"
with open(f"{path}/meta.json", "r") as f:
    meta = json.load(f)
mem_bandwidth = meta["measured_copy_bandwidth_gbps"]["torch.float32"]
mem_bandwidth_triton = meta["measured_copy_bandwidth_gbps"]["torch.float32"]

In [15]:
times = []
with open(f"{path}/times.jsonl", "r") as f:
    times = [json.loads(l) for l in f]
    
df = pd.DataFrame(times)
df.head()

,kernel_name,params,dtype,seed,times,flops,bytes_moved,device,run_id
0,vec_add_cuda_v1,{'N': 128},torch.float32,0,"[0.002623999956995249, 0.003247999935410917, 0...",128,1536,cuda:0,41b9e00b
1,vec_add_cuda_v1,{'N': 256},torch.float32,0,"[0.003008000086992979, 0.0035360000329092145, ...",256,3072,cuda:0,41b9e00b
2,vec_add_cuda_v1,{'N': 512},torch.float32,0,"[0.002976000076159835, 0.0035040000220760703, ...",512,6144,cuda:0,41b9e00b
3,vec_add_cuda_v1,{'N': 1024},torch.float32,0,"[0.0029120000544935465, 0.003600000054575503, ...",1024,12288,cuda:0,41b9e00b
4,vec_add_cuda_v1,{'N': 2048},torch.float32,0,"[0.0029440000653266907, 0.003648000070825219, ...",2048,24576,cuda:0,41b9e00b

In [16]:
df["p20_s"] = df.times.apply(lambda x: x[0] / 1e3)
df["med_s"] = df.times.apply(lambda x: x[1] / 1e3)
df["p80_s"] = df.times.apply(lambda x: x[2] / 1e3)
df["shape"] = df["params"].apply(lambda x: str(x["N"]))
df["kernel_name"] = df["kernel_name"].str.replace("vec_add_fwd", "vec_add_cuda_v1")
df["flops"] = df["shape"]
df["bytes_moved_gb"] = df["shape"].apply(lambda x: bytes_moved(shape=int(x)))
df["bandwidth_gbps"] = df["bytes_moved_gb"] / df["med_s"]
df["bandwidth_gbps_p20"] = df["bytes_moved_gb"] / df["p20_s"]
df["bandwidth_gbps_p80"] = df["bytes_moved_gb"] / df["p80_s"]
df["bandwidth_gbps_high"] = df["bandwidth_gbps_p80"] - df["bandwidth_gbps"]
df["bandwidth_gbps_low"] = df["bandwidth_gbps_p20"] - df["bandwidth_gbps"]
df.head()

,kernel_name,params,dtype,seed,times,flops,bytes_moved,device,run_id,p20_s,med_s,p80_s,shape,bytes_moved_gb,bandwidth_gbps,bandwidth_gbps_p20,bandwidth_gbps_p80,bandwidth_gbps_high,bandwidth_gbps_low
0,vec_add_cuda_v1,{'N': 128},torch.float32,0,"[0.002623999956995249, 0.003247999935410917, 0...",128,1536,cuda:0,41b9e00b,0.000003,0.000003,0.000004,128,0.000002,0.472906,0.585366,0.421053,-0.051854,0.112459
1,vec_add_cuda_v1,{'N': 256},torch.float32,0,"[0.003008000086992979, 0.0035360000329092145, ...",256,3072,cuda:0,41b9e00b,0.000003,0.000004,0.000004,256,0.000003,0.868778,1.021277,0.768000,-0.100778,0.152498
2,vec_add_cuda_v1,{'N': 512},torch.float32,0,"[0.002976000076159835, 0.0035040000220760703, ...",512,6144,cuda:0,41b9e00b,0.000003,0.000004,0.000004,512,0.000006,1.753425,2.064516,1.586777,-0.166648,0.311091
3,vec_add_cuda_v1,{'N': 1024},torch.float32,0,"[0.0029120000544935465, 0.003600000054575503, ...",1024,12288,cuda:0,41b9e00b,0.000003,0.000004,0.000004,1024,0.000012,3.413333,4.219780,3.173554,-0.239779,0.806447
4,vec_add_cuda_v1,{'N': 2048},torch.float32,0,"[0.0029440000653266907, 0.003648000070825219, ...",2048,24576,cuda:0,41b9e00b,0.000003,0.000004,0.000004,2048,0.000025,6.736842,8.347826,6.347108,-0.389734,1.610984

In [22]:
ADVERTISED_BW = 320

fig = go.Figure()
shapes = df["shape"].unique()
fig.add_traces(
    [
        go.Scatter(
            x=shapes,
            y=np.full_like(shapes, ADVERTISED_BW),
            mode="lines",
            name="Advertised Bandwidth",
        ),
        go.Scatter(
            x=shapes,
            y=np.full_like(shapes, mem_bandwidth),
            mode="lines",
            name="Measured Copy Bandwidth",
        ),
    ]
)

for kernel in df.kernel_name.unique():
    bw = df[df["kernel_name"] == kernel]["bandwidth_gbps"].values
    fig.add_trace(go.Scatter(x=shapes, y=bw, mode="lines+markers", name=kernel))
fig.update_layout({"title":"VecAdd Bandwidth"})
fig.show()

In [18]:
px.scatter(
    df,
    x="shape",
    y="bandwidth_gbps",
    error_y="bandwidth_gbps_high",
    error_y_minus="bandwidth_gbps_low",
    color="kernel_name",
    template="plotly_white",
    labels={"med": "Median runtime (s)"},
    title="VecAdd Sweep",
    facet_col="kernel_name",
).show()